on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+-*"
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
    - name: Build
      run: dotnet build --configuration Release /p:Version=${VERSION}
    - name: Test
      run: dotnet test --configuration Release /p:Version=${VERSION} --no-build

    # Axis.Dia.Core
    - name: Pack
      run: dotnet pack ./Dia/Axis.Dia.Core.csproj --configuration Release /p:Version=${VERSION} --output .
    - name: Push
      run: dotnet nuget push Axis.Dia.Core.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_TOKEN }}

    # Axis.Dia.PathQuery
    - name: Pack
      run: dotnet pack ./Dia/Axis.Dia.PathQuery.csproj --configuration Release /p:Version=${VERSION} --output .
    - name: Push
      run: dotnet nuget push Axis.Dia.PathQuery.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_TOKEN }}

    # Axis.Dia.AxonSerializer
    - name: Pack
      run: dotnet pack ./Dia/Axis.Dia.AxonSerializer.csproj --configuration Release /p:Version=${VERSION} --output .
    - name: Push
      run: dotnet nuget push Axis.Dia.AxonSerializer.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_TOKEN }}

    # Axis.Dia.BionSerializer
    - name: Pack
      run: dotnet pack ./Dia/Axis.Dia.BionSerializer.csproj --configuration Release /p:Version=${VERSION} --output .
    - name: Push
      run: dotnet nuget push Axis.Dia.BionSerializer.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_TOKEN }}

    # Axis.Dia.TyphonSerializer
    - name: Pack
      run: dotnet pack ./Dia/Axis.Dia.TyphonSerializer.csproj --configuration Release /p:Version=${VERSION} --output .
    - name: Push
      run: dotnet nuget push Axis.Dia.TyphonSerializer.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_TOKEN }}